use project1;

#1. What is the total Number of trips ( equal to number of rows)?
Select count(*) from taxidata;

#2. What is the total revenue generated by  all the trips ? Fare is stored in the column total_amount. 
Select sum(total_amount) as total_revenue from taxidata;

#3. What fraction of the total is paid for tolls? Toll is stored in tolls_amount.
Select sum(tolls_amount)/sum(total_amount) as toll_pct from taxidata;

#4. What fraction of it is driver tips? Tip is stored in tip_amount. 
Select sum(tip_amount)/sum(total_amount) as tip_pct from taxidata;

#5. What is the average trip amount?
Select avg(total_amount) as avg_tripamount from taxidata;

#6. For each payment type, display the following details 
#i.Average fare generated – fare amount is stored in fare_amount
#ii.Average tip 
#iii.Average tax – tax is stored in column mta_tax

select payment_type, avg(fare_amount) as average_fare, avg(tip_amount) as average_tip, avg(mta_tax) as average_tax from taxidata 
group by payment_type;

#7. On an average which hour of the day generates the highest revenue?

select h24 as hour, avg(total_amount) as avg_revenue from (select hour(tpep_pickup_datetime) as h24, total_amount from taxidata) ff
group by h24 order by avg_revenue desc;

#8. What is the average distance of the trips? Distance is stored in the column trip_distance. 
select avg(trip_distance) as avg_distance from taxidata;
 
 #9. How many different payment types are used? Column name – payment_type. 
select distinct payment_type from taxidata


